/*
 * This file is subject to the terms and conditions of the GNU General Public
 * License.  See the file "COPYING" in the main directory of this archive
 * for more details.
 *
 * Copyright (C) 2007 MIPS Technologies, Inc.
 * Copyright (C) 2007 Ralf Baechle <ralf@linux-mips.org>
 */
#include <linux/clockchips.h>
#include <linux/interrupt.h>
#include <linux/percpu.h>
#include <linux/smp.h>
#include <linux/irq.h>

#include <asm/time.h>
#include <asm/cevt-r4k.h>
#include <asm/gic.h>

static int mips_next_event(unsigned long delta,
			   struct clock_event_device *evt)
{
	unsigned int cnt;
	int res;

	cnt = read_c0_count();
	cnt += delta;
	write_c0_compare(cnt);
	res = ((int)(read_c0_count() - cnt) >= 0) ? -ETIME : 0;
	return res;
}

void mips_set_clock_mode(enum clock_event_mode mode,
				struct clock_event_device *evt)
{
	/* Nothing to do ...  */
}

DEFINE_PER_CPU(struct clock_event_device, mips_clockevent_device);
int cp0_timer_irq_installed;

/*
 * MIPS R4K CP0 Count/Compare Timer Interrupt Handler
 *
 * Hardware flow:
 *
 *   CP0_COUNT
 *        |
 *        | COUNT >= CP0_COMPARE
 *        |
 *        v
 *   Timer Interrupt (IP7)
 *        |
 *        v
 *   c0_compare_interrupt()
 *        |
 *        v
 *   clock_event_device->event_handler()
 *        |
 *        v
 *   tick_handle_periodic()
 *        |
 *        v
 *   scheduler_tick()
 *        |
 *        v
 *   CFS / PELT update
 *
 * For EcoNet EN7561DU:
 *
 *   MIPS32 1004Kc CPS
 *
 *   Core
 *    |
 *    +-- VPE0 -> Linux CPU0
 *    |
 *    +-- VPE1 -> Linux CPU1
 *
 * Each VPE has its own CP0_COUNT/COMPARE timer.
 */


 irqreturn_t c0_compare_interrupt(int irq, void *dev_id)
 {
	 /*
	  * MIPS architecture revision.
	  *
	  * MIPS32 Release 2 introduced additional interrupt status
	  * information, including performance counter pending bit.
	  *
	  * Older MIPS (R1):
	  *   Timer interrupt and performance counter interrupt
	  *   may share the same interrupt line.
	  */
	 const int r2 = cpu_has_mips_r2;
 
 
	 /*
	  * Linux generic clock event abstraction.
	  *
	  * This object represents the MIPS CP0 Count/Compare timer
	  * as a clock_event_device.
	  *
	  * Later this will call:
	  *
	  *     cd->event_handler(cd)
	  *
	  * which eventually reaches:
	  *
	  *     tick_handle_periodic()
	  *          |
	  *          +--> scheduler_tick()
	  *
	  */
	 struct clock_event_device *cd;
 
 
	 /*
	  * CP0 Count/Compare timer is per CPU.
	  *
	  * For MIPS1004K CPS:
	  *
	  *     VPE0 -> Linux CPU0
	  *     VPE1 -> Linux CPU1
	  *
	  * Each CPU has its own:
	  *
	  *     CP0_COUNT
	  *     CP0_COMPARE
	  *
	  */
	 int cpu = smp_processor_id();
 
 
 
	 /*
	  * ---------------------------------------------------------
	  * Handle Performance Counter Interrupt
	  * ---------------------------------------------------------
	  *
	  * Before MIPS32 Release 2:
	  *
	  * There was no hardware bit indicating whether
	  * Performance Counter interrupt was pending.
	  *
	  * Therefore when an interrupt arrives, Linux has to
	  * try the performance counter handler first.
	  *
	  * If performance counter interrupt was the real source:
	  *
	  *     handle_perf_irq()
	  *
	  * returns true and we finish here.
	  *
	  */
	 if (handle_perf_irq(r2))
		 goto out;
 
 
 
	 /*
	  * ---------------------------------------------------------
	  * Confirm this is really a Timer Interrupt
	  * ---------------------------------------------------------
	  *
	  * MIPS R2 provides Cause register information:
	  *
	  * CP0_CAUSE bit 30:
	  *
	  *     Performance Counter Interrupt Pending
	  *
	  *
	  * For R1:
	  *
	  *     !r2 == true
	  *
	  * because we cannot distinguish it.
	  *
	  *
	  * For R2:
	  *
	  *     read_c0_cause() & (1 << 30)
	  *
	  * confirms the interrupt source.
	  *
	  *
	  * Timer interrupt itself is:
	  *
	  *     CP0 Cause.IP7
	  *
	  * generated by:
	  *
	  *     CP0_COUNT >= CP0_COMPARE
	  *
	  */
	 if (!r2 || (read_c0_cause() & (1 << 30))) {
 
 
		 /*
		  * -----------------------------------------------------
		  * Clear Count/Compare Interrupt
		  * -----------------------------------------------------
		  *
		  * MIPS Timer interrupt condition:
		  *
		  *     COUNT >= COMPARE
		  *
		  *
		  * Example:
		  *
		  *     COUNT    = 100000
		  *     COMPARE  = 100000
		  *
		  * Timer IRQ becomes pending:
		  *
		  *     Cause.IP7 = 1
		  *
		  *
		  * If COMPARE is not acknowledged,
		  * the condition remains true and the CPU may
		  * repeatedly enter the interrupt handler.
		  *
		  *
		  * Writing COMPARE back acknowledges the timer event.
		  *
		  */
		 write_c0_compare(read_c0_compare());
 
 
 
		 /*
		  * Get this CPU's clock event device.
		  *
		  * Defined as:
		  *
		  * DEFINE_PER_CPU(
		  *      struct clock_event_device,
		  *      mips_clockevent_device);
		  *
		  *
		  * Example:
		  *
		  * CPU0:
		  *      mips_clockevent_device[0]
		  *
		  * CPU1:
		  *      mips_clockevent_device[1]
		  *
		  */
		 cd = &per_cpu(mips_clockevent_device, cpu);
 
 
 
		 /*
		  * Enter Linux clock event framework.
		  *
		  * Normally this eventually calls:
		  *
		  *     tick_handle_periodic()
		  *
		  * Then:
		  *
		  *     update_process_times()
		  *
		  * Then:
		  *
		  *     scheduler_tick()
		  *
		  * Finally:
		  *
		  *     task_tick_fair()
		  *
		  *     update_load_avg()
		  *
		  *     PELT update
		  *
		  */
		 cd->event_handler(cd);
	 }
 
 
 out:
 
	 /*
	  * Tell Linux IRQ subsystem:
	  *
	  * This interrupt has been handled.
	  *
	  */
	 return IRQ_HANDLED;
 }

struct irqaction c0_compare_irqaction = {
	.handler = c0_compare_interrupt,
	.flags = IRQF_PERCPU | IRQF_TIMER,
	.name = "timer",
};


void mips_event_handler(struct clock_event_device *dev)
{
}

/*
 * FIXME: This doesn't hold for the relocated E9000 compare interrupt.
 */
static int c0_compare_int_pending(void)
{
#ifdef CONFIG_IRQ_GIC
	if (cpu_has_veic)
		return gic_get_timer_pending();
#endif
	return (read_c0_cause() >> cp0_compare_irq_shift) & (1ul << CAUSEB_IP);
}

/*
 * Compare interrupt can be routed and latched outside the core,
 * so wait up to worst case number of cycle counter ticks for timer interrupt
 * changes to propagate to the cause register.
 */
#define COMPARE_INT_SEEN_TICKS 50

int c0_compare_int_usable(void)
{
	unsigned int delta;
	unsigned int cnt;

#ifdef CONFIG_KVM_GUEST
    return 1;
#endif

	/*
	 * IP7 already pending?	 Try to clear it by acking the timer.
	 */
	if (c0_compare_int_pending()) {
		cnt = read_c0_count();
		write_c0_compare(cnt);
		back_to_back_c0_hazard();
		while (read_c0_count() < (cnt  + COMPARE_INT_SEEN_TICKS))
			if (!c0_compare_int_pending())
				break;
		if (c0_compare_int_pending())
			return 0;
	}

	for (delta = 0x10; delta <= 0x400000; delta <<= 1) {
		cnt = read_c0_count();
		cnt += delta;
		write_c0_compare(cnt);
		back_to_back_c0_hazard();
		if ((int)(read_c0_count() - cnt) < 0)
		    break;
		/* increase delta if the timer was already expired */
	}

	while ((int)(read_c0_count() - cnt) <= 0)
		;	/* Wait for expiry  */

	while (read_c0_count() < (cnt + COMPARE_INT_SEEN_TICKS))
		if (c0_compare_int_pending())
			break;
	if (!c0_compare_int_pending())
		return 0;
	cnt = read_c0_count();
	write_c0_compare(cnt);
	back_to_back_c0_hazard();
	while (read_c0_count() < (cnt + COMPARE_INT_SEEN_TICKS))
		if (!c0_compare_int_pending())
			break;
	if (c0_compare_int_pending())
		return 0;

	/*
	 * Feels like a real count / compare timer.
	 */
	return 1;
}

int r4k_clockevent_init(void)
{
	unsigned int cpu = smp_processor_id();
	struct clock_event_device *cd;
	unsigned int irq;

	if (!cpu_has_counter || !mips_hpt_frequency)
		return -ENXIO;

	if (!c0_compare_int_usable())
		return -ENXIO;

	/*
	 * With vectored interrupts things are getting platform specific.
	 * get_c0_compare_int is a hook to allow a platform to return the
	 * interrupt number of it's liking.
	 */
	irq = MIPS_CPU_IRQ_BASE + cp0_compare_irq;
	if (get_c0_compare_int)
		irq = get_c0_compare_int();

	cd = &per_cpu(mips_clockevent_device, cpu);

	cd->name		= "MIPS";
	cd->features		= CLOCK_EVT_FEAT_ONESHOT |
				  CLOCK_EVT_FEAT_C3STOP |
				  CLOCK_EVT_FEAT_PERCPU;

	clockevent_set_clock(cd, mips_hpt_frequency);

	/* Calculate the min / max delta */
	cd->max_delta_ns	= clockevent_delta2ns(0x7fffffff, cd);
	cd->min_delta_ns	= clockevent_delta2ns(0x300, cd);

	cd->rating		= 300;
	cd->irq			= irq;
	cd->cpumask		= cpumask_of(cpu);
	cd->set_next_event	= mips_next_event;
	cd->set_mode		= mips_set_clock_mode;
	cd->event_handler	= mips_event_handler;

	clockevents_register_device(cd);

	if (cp0_timer_irq_installed)
		return 0;

	cp0_timer_irq_installed = 1;

	setup_irq(irq, &c0_compare_irqaction);

	return 0;
}

